# Generated by Django 4.1.13 on 2024-12-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='abcd_parent_ids',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_id', models.CharField(blank=True, db_column='table_primary_key', max_length=100, null=True)),
                ('parameter', models.CharField(blank=True, db_column='table', max_length=500, null=True)),
            ],
            options={
                'db_table': 'abcd_parent_ids',
            },
        ),
    ]
