# Generated by Django 4.1.13 on 2024-12-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_abcd_parent_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abcd_parent_ids',
        ),
    ]
