# Generated by Django 4.1.13 on 2024-12-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_abcd_parent_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard_data',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='dashboard_data',
            name='server_id',
        ),
        migrations.RemoveField(
            model_name='sheet_data',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='sheet_data',
            name='server_id',
        ),
        migrations.AddField(
            model_name='dashboard_data',
            name='hierarchy_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sheet_data',
            name='hierarchy_id',
            field=models.IntegerField(default=None),
        ),
    ]
