# Generated by Django 4.1.13 on 2024-12-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_dashboard_data_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_data',
            name='hierarchy_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
