# Generated by Django 4.1.13 on 2024-12-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_dashboard_data_hierarchy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation_field',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='calculation_field',
            name='server_id',
        ),
        migrations.AddField(
            model_name='calculation_field',
            name='hierarchy_id',
            field=models.IntegerField(default=None),
        ),
    ]
