# Generated by Django 4.1.13 on 2024-12-13 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_calculation_field_file_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custome_theme_data',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('navigation_styles', models.CharField(blank=True, db_column='navigation_styles', max_length=500, null=True)),
                ('primary_column_theme', models.CharField(blank=True, db_column='primary_column_theme', max_length=500, null=True)),
                ('menu_colours', models.CharField(blank=True, db_column='menu_colours', max_length=500, null=True)),
                ('header_colours', models.CharField(blank=True, db_column='header_colours', max_length=500, null=True)),
                ('textcolour', models.CharField(blank=True, db_column='textcolour', max_length=500, null=True)),
                ('background_colour', models.CharField(blank=True, db_column='background_colour', max_length=500, null=True)),
            ],
            options={
                'db_table': 'custome_theme_data',
            },
        ),
    ]
