# Generated by Django 4.1.13 on 2024-12-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_custome_theme_data_primary_column_theme_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userconfigurations',
            table='userconfigurations',
        ),
    ]
