# Generated by Django 4.1.13 on 2024-12-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_custome_theme_data_textcolour_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userconfigurations',
            table='userconfigurations',
        ),
    ]
