# Generated by Django 4.1.13 on 2024-12-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_custome_theme_data_background_colour_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userconfigurations',
            table='user_chart_plugins',
        ),
    ]
