# Generated by Django 4.1.13 on 2024-12-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_userconfigurations_table'),
    ]

    operations = [
    ]
