# Generated by Django 4.1.13 on 2024-12-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_custome_theme_data_background_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardfilters',
            name='selected_query',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardfilters',
            name='queryset_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
