# Generated by Django 4.1.13 on 2025-01-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_dashboardfilters_selected_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardfilters',
            name='hierarchy_id',
            field=models.IntegerField(null=True),
        ),
    ]
