# Generated by Django 4.1.13 on 2025-01-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_dashboardfilters_hierarchy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_ids',
            name='table_id',
            field=models.IntegerField(blank=True, db_column='table_primary_key', null=True),
        ),
    ]
