# Generated by Django 4.1.13 on 2025-01-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_parent_ids_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartfilters',
            name='top_bottom',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
