# Generated by Django 4.1.13 on 2025-01-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_chartfilters_top_bottom'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_drill_through',
            name='hierarchy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard_drill_through',
            name='queryset_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
