# Generated by Django 4.1.13 on 2025-01-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_dashboard_drill_through_hierarchy_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_ids',
            name='table_id',
            field=models.CharField(blank=True, db_column='table_primary_key', max_length=100, null=True),
        ),
    ]
