# Generated by Django 4.1.13 on 2025-02-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_datasourcefilter_is_exclude'),
    ]

    operations = [
        migrations.CreateModel(
            name='cross_db_ids',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hierarchy_ids', models.TextField(blank=True, db_column='hierarchy_ids', null=True)),
            ],
            options={
                'db_table': 'cross_database_ids',
            },
        ),
        migrations.AddField(
            model_name='parent_ids',
            name='is_cross_database',
            field=models.BooleanField(default=False),
        ),
    ]
