# Generated by Django 4.1.13 on 2025-02-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_cross_db_ids_parent_ids_is_cross_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetfilter_querysets',
            name='pivot_measure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
