# Generated by Django 4.1.13 on 2025-02-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_sheetfilter_querysets_pivot_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartfilters',
            name='relative_date',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
