# Generated by Django 4.1.13 on 2024-09-16 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0032_alter_tokenstoring_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenstoring',
            name='token_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokenstoring',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 12, 34, 30, 923679)),
        ),
        migrations.AlterField(
            model_name='tokenstoring',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 13, 34, 30, 923679)),
        ),
        migrations.AlterField(
            model_name='tokenstoring',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 12, 34, 30, 923679)),
        ),
    ]
