"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import datetime
import base64

encoded_string='bG9jYWxob3N0OmNoZXBwYW51OjgwMDA='
decoded_bytes = base64.b64decode(encoded_string.encode('utf-8'))
decoded_string = decoded_bytes.decode('utf-8')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$!va8pxb&5j9%67x)8t1&zr_xa@w+c@kteqeat!r2(94#s=pf$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost']

AUTH_USER_MODEL = "dashboard.UserProfile"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
    'quickbooks',
    'copilot',
    'sample',
    
    'rest_framework',
    'rest_framework.authtoken',
    'knox',
    'corsheaders',
    'oauth2_provider',
    'drf_yasg',
]


# Email Configrations
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('ADMIN_EMAIL') # Add Authorized Email
EMAIL_HOST_PASSWORD = os.environ.get('ADMIN_PASSWORD') #Add Authorized Password


# If you want to allow access for all domains, set the following variable to TRUE
CORS_ORIGIN_ALLOW_ALL = True

CORS_ORIGIN_WISHLIST = [
    'http://localhost:4200',
    'http://127.0.0.1:5000',
    'http://127.0.0.1:8000',
    '*',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    #CORS MiddleWare
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main.sqlite3',
    },
       'example': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'insightapps-sample',
    }
}

DATABASE_ROUTERS = ['dashboard.router.DatabaseRouter']

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECURE_CROSS_ORIGIN_OPENER_POLICY=None

# Value determines whether the server allows cookies in the cross-site HTTP requests
CORS_ALLOW_CREDENTIALS = True

# Methods allowed for CORS
CORS_ALLOW_METHODS = [
    'DELETE',
    'OPTIONS',
    'PATCH',
    'GET',
    'POST',
    'PUT',  
]

# Non-standard headers allowed in the request
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]



expiry_time=datetime.datetime.now()+datetime.timedelta(seconds=3600)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ),
}

AWS_S3_ACCESS_KEY_ID = ''
AWS_S3_SECRET_ACCESS_KEY = ''
AWS_STORAGE_BUCKET_NAME = ''
AWS_S3_REGION_NAME = '' 


SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
}

perpage = 10  ## for pagination

db_connections=10

ENVIRONMENT = 'sandbox'

# Domain auto update in urls
# accept any https domain in developer portal

if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    link_url = 'http://localhost:8080/' # example frontend URL for local 
    TOKEN_URL = 'http://localhost:8000/v1/oauth2/token/' # example backend URL for local


SANDBOX_URL = ''
SANDBOX_QUICKBOOKS_ID = ''
SANDBOX_QUICKBOOKS_SECRET = ''
SANDBOX_REDIRECT_URL = '' #### https://api.insightapps.ai/authentication/quickbooks/
SANDBOX_SCOPES = []
token_url='https://www.google.com/'


# link_url = 'http://54.67.88.195:4200/'

file_save_url = 'http://localhost:8000/'

file_save_path = 'local'  # local #s3

#######  oauth2  #######
# TOKEN_URL = 'http://13.57.231.251:50/v1/oauth2/token/'


OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 57600,  # Access token expiration time (in seconds)
    'REFRESH_TOKEN_EXPIRE_SECONDS': 86400,  # Refresh token expiration time (in seconds)
}


SALESFORCE_CONSUMER_KEY = ''
SALESFORCE_CONSUMER_SECRET = ''
SALESFORCE_REDIRECT_URI = '' 
SALESFORCE_AUTH_URL = ''
SALESFORCE_TOKEN_URL = ''
SALESFORCE_DOMAIN = ''


DEFAULT_TOKEN = "B8nGJ4oIRfujTrmosWBAN54zatfn9J"



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

