# Generated by Django 4.1.13 on 2024-12-06 07:34

from django.db import migrations, models
import django.utils.timezone
import quickbooks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenStoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.IntegerField(blank=True, db_column='user_id', null=True)),
                ('parameter', models.CharField(blank=True, max_length=100, null=True)),
                ('qbuserid', models.CharField(blank=True, db_column='quickbooks_user_id', max_length=1000, null=True)),
                ('salesuserid', models.CharField(blank=True, db_column='salesforce_user_id', max_length=1000, null=True)),
                ('tokentype', models.CharField(blank=True, db_column='token_type', max_length=100, null=True)),
                ('accesstoken', models.CharField(blank=True, db_column='access_token', max_length=1800, null=True)),
                ('refreshtoken', models.CharField(blank=True, db_column='refresh_token', max_length=1800, null=True)),
                ('idtoken', models.CharField(blank=True, db_column='id_token', max_length=1800, null=True)),
                ('realm_id', models.CharField(blank=True, db_column='realm_id', max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, db_column='display_name', max_length=1000, null=True)),
                ('token_code', models.TextField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(default=quickbooks.models.get_expiry_date)),
            ],
            options={
                'db_table': 'access_tokens',
            },
        ),
    ]
