# Generated by Django 4.1.13 on 2024-12-24 12:24

from django.db import migrations, models
import django.utils.timezone
import quickbooks.models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0002_connectwise'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaloPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('site_url', models.TextField(blank=True, null=True)),
                ('client_id', models.TextField(blank=True, null=True)),
                ('client_secret', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('expiry_date', models.DateTimeField(default=quickbooks.models.get_expiry_date)),
            ],
            options={
                'db_table': 'HaloPs',
            },
        ),
        migrations.RenameField(
            model_name='connectwise',
            old_name='company_name',
            new_name='display_name',
        ),
    ]
