# Generated by Django 4.1.13 on 2025-01-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0003_halops_rename_company_name_connectwise_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenstoring',
            name='domain_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
