# Generated by Django 4.1.13 on 2025-01-21 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0004_tokenstoring_domain_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('display_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('api_token', models.TextField(blank=True, null=True)),
                ('shop_name', models.TextField(blank=True, null=True)),
                ('api_version', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Shopify',
            },
        ),
    ]
