# Generated by Django 4.1.13 on 2025-02-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0005_shopify'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenstoring',
            name='google_spreadsheet_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
