# Generated by Django 4.1.13 on 2024-09-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_alter_account_activation_created_at_and_more'),
        ('dashboard', '0097_alter_account_activation_created_at_and_more'),
    ]

    operations = [
    ]
