# Generated by Django 4.1.13 on 2024-10-10 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0099_chartfilters_is_exclude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartfilters',
            name='is_exclude',
            field=models.BooleanField(default=False, null=True),
        )
    ]
