# Generated by Django 4.1.13 on 2024-10-14 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0101_modules_alter_account_activation_created_at_and_more'),
    ]

    operations = [
    ]
