# Generated by Django 4.1.13 on 2024-10-16 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0103_alter_account_activation_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='angular_icon',
        ),
        migrations.AddField(
            model_name='modules',
            name='css_classes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='image_urls',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userguide',
            name='module_id',
            field=models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.modules'),
        ),
    ]
