# Generated by Django 4.1.13 on 2024-10-18 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0103_alter_account_activation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license_key',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 18, 4, 51, 35, 700678, tzinfo=datetime.timezone.utc)),
        ),
    ]
