# Generated by Django 4.1.13 on 2024-10-18 04:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0104_alter_account_activation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license_key',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
