# Generated by Django 4.1.13 on 2024-10-18 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0106_alter_account_activation_created_at_and_more'),
    ]

    operations = [
    ]
