# Generated by Django 4.1.13 on 2024-10-18 05:16

import dashboard.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0107_alter_account_activation_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_activation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=dashboard.models.get_expiry_date),
        ),
    ]
