# Generated by Django 4.1.13 on 2024-10-18 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_account_activation_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_activation',
            name='updated_at',
        ),
    ]
