# Generated by Django 4.1.13 on 2024-10-18 05:35

import dashboard.models
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0109_remove_account_activation_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Activation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.IntegerField(db_column='user_id', null=True)),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('otp', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(default=dashboard.models.get_expiry_date)),
            ],
            options={
                'db_table': 'account_activation1',
            },
        ),
    ]
