# Generated by Django 4.1.13 on 2024-10-18 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_account_activation1_alter_chartfilters_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account_Activation1',
        ),
        migrations.AddField(
            model_name='account_activation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
