# Generated by Django 4.1.13 on 2024-10-18 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0111_delete_account_activation1_and_more'),
    ]

    operations = [
    ]
