# Generated by Django 4.1.13 on 2024-10-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0104_remove_modules_angular_icon_modules_css_classes_and_more'),
        ('dashboard', '0112_alter_chartfilters_created_at_and_more'),
    ]

    operations = [
    ]
