# Generated by Django 4.1.13 on 2024-10-22 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0113_merge_20241022_1118'),
    ]

    operations = [
    ]
