# Generated by Django 4.1.13 on 2024-10-23 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0115_alter_chartfilters_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('chart_type', models.CharField(choices=[('echart', 'Echart'), ('apex', 'Apex')], default='echart', max_length=200)),
            ],
            options={
                'db_table': 'user_configurations',
            },
        )    ]
