# Generated by Django 4.1.13 on 2024-11-05 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0116_userconfigurations_alter_chartfilters_created_at_and_more'),
    ]

    operations = [
    ]
