# Generated by Django 4.1.13 on 2024-11-26 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0118_alter_chartfilters_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='calculation_field',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('queryset_id', models.IntegerField(blank=True, null=True)),
                ('server_id', models.IntegerField(blank=True, null=True)),
                ('file_id', models.IntegerField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, max_length=500, null=True)),
                ('cal_logic', models.TextField(blank=True, db_column='calculation_logic', null=True)),
            ],
            options={
                'db_table': 'calculation_field',
            },
        ),
    ]
