# Generated by Django 4.1.13 on 2024-11-29 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0120_alter_chartfilters_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartfilters',
            name='field_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chartfilters',
            name='is_calculated',
            field=models.BooleanField(default=False, null=True),
        )
    ]
