# Generated by Django 4.1.13 on 2024-11-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0121_alter_chartfilters_created_at_and_more'),
        ('dashboard', '0121_chartfilters_field_name_chartfilters_is_calculated_and_more'),
    ]

    operations = [
    ]
