# Generated by Django 4.1.13 on 2024-11-29 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0122_merge_20241129_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartfilters',
            old_name='field_name',
            new_name='field_logic',
        )
    ]
