# Generated by Django 4.1.13 on 2024-11-29 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0123_rename_field_name_chartfilters_field_logic_and_more'),
    ]

    operations = [
        
    ]
