# Generated by Django 4.1.13 on 2024-12-02 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0124_alter_chartfilters_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_drill_through',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('action_name', models.CharField(blank=True, max_length=500, null=True)),
                ('queryset_id', models.IntegerField(blank=True, null=True)),
                ('dashboard_id', models.IntegerField(blank=True, null=True)),
                ('source_sheet_id', models.IntegerField(blank=True, db_column='source_sheet_id', null=True)),
                ('target_sheet_id', models.TextField(blank=True, db_column='target_sheet_id', null=True)),
            ],
            options={
                'db_table': 'dashboard_drill_through_data',
            },
        ),
    ]
