# Generated by Django 4.1.13 on 2024-12-03 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0126_calculation_field_functionname_and_more'),
    ]

    operations = [
    ]
