# Generated by Django 4.1.13 on 2024-12-03 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0127_alter_chartfilters_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation_field',
            name='actual_dragged_logic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
