# Generated by Django 4.1.13 on 2024-09-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptapikey',
            name='api_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gptapikey',
            name='api_key_status',
            field=models.BooleanField(default=False),
        ),
    ]
