# Generated by Django 4.1.13 on 2024-09-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0004_alter_gptapikey_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptapikey',
            name='added_by',
            field=models.IntegerField(unique=True),
        ),
    ]
