# Generated by Django 4.1.13 on 2024-12-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_quickbooks_salesforce'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbooks',
            name='pr_Id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='salesforce',
            name='pr_Id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
