# Generated by Django 4.1.13 on 2024-12-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_quickbooks_pr_id_salesforce_pr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesforce',
            name='UserPermissionsCallCenterAutoLogin',
        ),
        migrations.RemoveField(
            model_name='salesforce',
            name='UserPermissionsMarketingUser',
        ),
        migrations.RemoveField(
            model_name='salesforce',
            name='UserPermissionsOfflineUser',
        ),
        migrations.RemoveField(
            model_name='salesforce',
            name='UserPreferencesActivityRemindersPopup',
        ),
        migrations.RemoveField(
            model_name='salesforce',
            name='UserRoleId',
        ),
        migrations.RemoveField(
            model_name='salesforce',
            name='UserType',
        ),
    ]
